spring.application.name=order-service
server.port=${PORT:8081}
spring.mvc.problemdetails.enabled=true
product-service.base-url=${PRODUCT_SERVICE_URL:http://localhost:8080}
payment-service.base-url=${PAYMENT_SERVICE_URL:http://localhost:8082}
frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}
