spring.application.name=product-service
server.port=${PORT:8080}
frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reacspi}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:reacspi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:reacspi}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=product_service
spring.flyway.default-schema=product_service
spring.flyway.schemas=product_service
